### ISSUE TITLE
Remove existing Webpaths which serve no purpose

### ISSUE THREAD

**Issue by carlosparadis** [erdl/survey_admin#1]
Jason identified 2 web paths in the survey admin that are displayed if the user specifies the path, but serve no purpose:

 * /test
    * Template: sortable_test.html
 * /index
    * Template: index.html

**views.py** must also be updated to reflect the removal of these URL paths.

**Comment by jygh98** [comment]
@carlosparadis 
After reviewing the files it appears that these are indeed test webpaths
