### ISSUE TITLE
add OAuth for user login

### ISSUE THREAD

**Issue by jygh98** [erdl/survey_admin#23]
OAuth (Open Authorization) is an open standard for token-based authentication and authorization on the Internet which will allows an end user's account information to be used by third-party services, such as Google, without exposing the user's password. OAuth acts as an intermediary on behalf of the end user, providing the service with an access token that authorizes specific account information to be shared. 

The motive for this feature is allow for Google to authenticate users on our behalf and thus ensuring proper security for our admin dashboard website.  With this we plan to move features such as adding new questions directly on the dashboard through the added security provided by Google.  The login page will adjusted to login through your Google account and only authorized emails will be given access. 

https://www.udacity.com/course/authentication-authorization-oauth--ud330

**Comment by jygh98** [comment]
OAuth (Open Authorization) is an open standard for token-based authentication and authorization on the Internet which will allows an end user's account information to be used by third-party services, such as Google, without exposing the user's password. OAuth acts as an intermediary on behalf of the end user, providing the service with an access token that authorizes specific account information to be shared. 

https://www.udacity.com/course/authentication-authorization-oauth--ud330

**Comment by jygh98** [comment]
https://stackoverflow.com/questions/12909332/how-to-logout-of-an-application-where-i-used-oauth2-to-login-with-google

https://stackoverflow.com/questions/15520361/permission-denied-for-relation

http://bitwiser.in/2015/09/09/add-google-login-in-flask.html
  
https://dba.stackexchange.com/questions/65662/postgres-how-to-insert-row-with-autoincrement-id

**Comment by jygh98** [comment]
# Documentation
## Querying the Database to check if the user's email is whitelisted
Despite Google's OAuth ability to allow/restrict specific domain name, there is currently no feature from Google that allows you develop an admin panel for the project such that Google OAuth will only permit specific email addresses.  For this, the appropriate step was for the flask app to query the database for a list of permitted user email which other people have done as well.  
[[1] Google OAuth Limiting Login to Specific Domain Name](https://stackoverflow.com/questions/10858813/restrict-login-email-with-google-oauth2-0-to-specific-domain-name)
[[2] Not possible to allow only whitelisted emails to login via Google Developer Console](https://stackoverflow.com/questions/47902578/google-oauth-login-how-to-allow-only-whitelisted-emails-to-log-into-my-app)
[[3] How to restrict Google OAuth login to specific emails](https://stackoverflow.com/questions/34235590/how-do-you-restrict-google-login-oauth2-to-emails-from-a-specific-google-apps)

**Comment by carlosparadis** [comment]
I suppose this still works for us. Anyone can do a brute force to guess a password given an user name to get access. But if we have stored the e-mails, even if the e-mails were public and an attacker had it, they would still need to prove to Google they own the said e-mail. Good luck on that fight to them. 

How hard is to replace the existing login and password to an e-mail database?

**Comment by ryantanaka** [comment]
@ryantanaka confirm that we can add users manually through the datbase

**Comment by carlosparadis** [comment]
@ryantanaka @jygh98  PR #24 has wrongly 4 commits that pertain to this issue.

**Comment by carlosparadis** [comment]
Since this issue was completed, and it's PR accepted (in spite of using the wrong issue code to 24), I am closing it. However, it generated a new one which I will open a separate issue to go about. Specifically: 

https://github.com/erdl/survey_admin/blob/c18233a05a1038426027bb06cea0e7ae3f6e1e30/run.py#L5

Is required, as we currently do not own a SSL Certificate. Will discuss implications and what this means on a new issue, and reference this one from there.
