### ISSUE TITLE
Create page that allows to add question

### ISSUE THREAD

**Issue by jygh98** [erdl/survey_admin#29]
With OAuth now being implemented as authorization to survey admin, we can now continue with re-implementing the feature that allows us to directly add questions on the site.  The motive for this was that previously to add a new question to the survey panel, you would needed to manually insert it through the database.

**Comment by jygh98** [comment]
# Notes
- form.option.data is queried as option_id, need to find some way to query the text that can then be inserted.  
> select text from option where option_id=form.option.data;

iterate the list with sqlalchemy to return all text
- find out what to do with values, response_position and option_color columns

**Comment by jygh98** [comment]
CSRF token is not being included during ajax post request, to fix:
1. Add a function that when an ajax request is made it will pass along the CSRF token
2. Exempt the view from csrf token needed
[[1] Reference Links](https://www.google.com/search?q=ajax+post+request+add+csrf+token&oq=ajax+post+request+add+csrf+token&aqs=chrome..69i57.3647j0j7&sourceid=chrome&ie=UTF-8)
[[2] Dynamic Flask Form Repo](https://github.com/sebkouba/dynamic-flask-form)

**Comment by carlosparadis** [comment]
@jygh98 This issue needs a bit more context (including the title), as it stands it looks more an entire note to yourself! :| Is this the issue about `Creating a page to add questions` which was dependent on the `Oauth` issue? (What was that issue again? If it is not, then don't link or Github will permanently hook them up!)

**Comment by carlosparadis** [comment]
My understanding is that this issue is done, @jygh98 @ryantanaka please re-open otherwise.
