### ISSUE TITLE
Update database to work with Oauth

### ISSUE THREAD

**Issue by ryantanaka** [erdl/survey_admin#47]
@jygh98, can you meet this Thursday 3:00pm so we can update the database on the server to work with Oauth? Once we pull your merged changes onto the server, we can make sure all the functionalities are working properly and get #40, #33, #31, #29, #23, #7 closed on the issues list.

**Comment by jygh98** [comment]
@ryantanaka 👍

**Comment by carlosparadis** [comment]
As discussed today with @jygh98 , my understanding is that a new table `oauth` was created. But the current status of the `user` and `users` table which is no longer used by survey_admin (or any other app on the server), remains. Can someone confirm? I would like to keep dead code and tables to a minimum to avoid ambiguity and confusion down the road.

**Comment by ryantanaka** [comment]
@ryantanaka

note 3/2/18:

Still need to do #40, #33, #31, #29

**Comment by ryantanaka** [comment]
@carlosparadis, You are right about the `oauth` table. I confirmed that `users` is not needed. I will go ahead and remove it from the database. 

@jygh98, hey jason, am i missing something? i can't seem to find code referencing to the `is_deployed` column of the `deployed_url` table or any type of feature associated to #40 when running the web app locally. is #40 done or do I need to code that up? LMK, thanks

**Comment by ryantanaka** [comment]
@jygh98, actually nvm I see the code on your fork `33-allow-to-edit-survey-admin`.

**Comment by jygh98** [comment]
@ryantanaka  :+1:

**Comment by ryantanaka** [comment]
the database is set up with the oauth table (both jason and I are added at the moment), I am closing this issue
