### ISSUE TITLE
Accidentally removed HTTPError import while solving merge conflict 

### ISSUE THREAD

**Issue by jygh98** [erdl/survey_admin#48]
when testing on the server, we encountered a name error for HTTPError as the library needed to be imported.

**Comment by carlosparadis** [comment]
Confirmed with @jash98 today that during the merge conflict the import code line was removed, which made the following lines of code, which relies on `HTTPErrror` break:

https://github.com/erdl/survey_admin/blob/c18233a05a1038426027bb06cea0e7ae3f6e1e30/ubuntuStation/views.py#L81-L82

Commit 08c326d addresses that.
