### ISSUE TITLE
Need to organize ubuntuStation

### ISSUE THREAD

**Issue by ryantanaka** [erdl/survey_admin#53]
1. `ubuntuStation/static` needs to be reorganized such that js, css, images, and html files are in their own  directory
- this will help to keep our directory clean and organized 
2. css specific to `survey_admin` needs to be removed from `boostrap.css` and placed in their own respective css files in `ubuntuStation/static/stylesheets/` 
- application specific css should **not** be in the bootstrap.css library
- lines that need to be taken out  can be found at these commits:
https://github.com/erdl/survey_admin/commit/7de0a808546b87314fb8c19eaff9d8cdfe21335b
https://github.com/erdl/survey_admin/commit/f3496120367e386ef8758824a7599d0c8fc501c5
https://github.com/erdl/survey_admin/commit/9a2c90a77697ec594ef4da9bf9288fa5295e4dc7

I confirmed with Jason that these were the only additions.  Confirmed here as well:

https://github.com/erdl/survey_admin/commits/master/ubuntuStation/static/bootstrap.css

3. remove unused css files `bootstrap.css.1` and `bootstrap.css.2`

4. `ubuntuStation` needs to be renamed to `survey_admin` for consistency
- make sure this doesn't break anything in terms of the code and the Apache server
   
```
 15     # admin dashboard
 16     WSGIScriptAlias / /var/www/ubuntuStation/ubuntustation.wsgi
 17     <Directory /var/www/ubuntuStation/ubuntuStation/>
 18         Order allow,deny
 19         Allow from all
 20     </Directory>
 21     # admin dashboard static files
 22     Alias /static /var/www/ubuntuStation/ubuntuStation/static
 23     <Directory /var/www/ubuntuStation/ubuntuStation/static/>
 24         Order allow,deny
 25         Allow from all
 26     </Directory>
```
 needs to be updated to reflect the change in directory name

**Comment by carlosparadis** [comment]
@ryantanaka While you are at it, can you get rid of the `ubuntuStation` folder and refer it as `survey_admin`? This is way overdue on our wish list :^) May need to change on the server outer folder as well and may  need to double check the Apache HTTP.

**Comment by ryantanaka** [comment]
@carlosparadis , got it I updated the issue

btw so when you say
> double check the Apache HTTP

Does this mean what I wrote up there in the  first issue comment under bullet point number 3? This doesn't have to do with HTTPS right?

**Comment by carlosparadis** [comment]
@ryantanaka negative, I am referring to the re-route it happens for both web-apps sharing the same domain. I am not sure if the folder path is used there.

**Comment by ryantanaka** [comment]
@carlosparadis, ok gotcha, yeah looks like I will need to update the  `/etc/apache2/sites-enabled/csbcd-survey-apps.conf`

this part in particular:
```
 15     # admin dashboard
 16     WSGIScriptAlias / /var/www/ubuntuStation/ubuntustation.wsgi
 17     <Directory /var/www/ubuntuStation/ubuntuStation/>
 18         Order allow,deny
 19         Allow from all
 20     </Directory>
 21     # admin dashboard static files
 22     Alias /static /var/www/ubuntuStation/ubuntuStation/static
 23     <Directory /var/www/ubuntuStation/ubuntuStation/static/>
 24         Order allow,deny
 25         Allow from all
 26     </Directory>
```

**Comment by carlosparadis** [comment]
I am closing the issues referring by the last accepted PR. Please re-open if you believe is unfinished.
