### ISSUE TITLE
Update code that uses 'is_kioski' to use 'is_kiosk' 

### ISSUE THREAD

**Issue by ryantanaka** [erdl/survey_admin#56]
Source code and some html files need to be changed to reflect the change in the database.

This is in response to erdl/database#10

The values returned by RadioFiled also needs to be boolean. (The change has been made. Adding it here so I can reference the commit)

https://github.com/erdl/survey_admin/blob/49727d1e9bb31e709bc3206896f6098e4aa43c02/ubuntuStation/forms.py#L68

**Comment by carlosparadis** [comment]
I am closing the issues referring by the last accepted PR. Please re-open if you believe is unfinished.
