### ISSUE TITLE
Need to handle raised exception in the route for /deploymentform

### ISSUE THREAD

**Issue by ryantanaka** [erdl/survey_admin#57]
Adding an entry to `kiosk.deployed_url` means that the `kiosk.kiosk_survey` table must be updated as well. In the snippet bellow, the nested try block defeats that purpose. Several things could happen here.
**1** Add a deployed_url, that fails, the `finally block` is executed, that fails, and an exception is raised on line 191 and the program crashes
**2** Add a deployed_url, finally block fails, exception is raised and the program crashes

Nothing outside of the function catches the `raise` on line 191 (i tried by just calling raise at the beginning of the function). It would be nice to make it so that the program rolls back  both of the postgres operations without crashing the program in the event that an add to `kiosk.deployed_url` or `kiosk.kiosk_survey` fails. (The code is written, just adding the issue here so I can reference it)

https://github.com/erdl/survey_admin/blob/49727d1e9bb31e709bc3206896f6098e4aa43c02/ubuntuStation/views.py#L170-L197

**Comment by carlosparadis** [comment]
I am closing the issues referring by the last accepted PR. Please re-open if you believe is unfinished.
