### ISSUE TITLE
Database schema on github does not match with schema on production

### ISSUE THREAD

**Issue by jygh98** [erdl/survey_admin#6]
file on [GitHub schema.sql](https://github.com/CSBCD-SOEST/ubuntuStation/blob/master/ubuntuStation/schema.sql)

**Comment by jygh98** [comment]
@carlosparadis 
Looks like this issue has been resolved from when we synced survey admin with the repository?

**Comment by carlosparadis** [comment]
this issue will be followed up with you and @kathrynparadis so that we can get a folder like the `dhhl` but for `survey_admin` which should resemble somehow the `Schema block` from the `master schema` shown at: https://github.com/erdl/database

**Comment by carlosparadis** [comment]
I am closing this issue for now, as there are plans in place to revisit the database even for scrape-util. Once the dust settles, we can either re-open this or create a new issue to reflect the current situation.
