### ISSUE TITLE
Can't log into Survey Admin

### ISSUE THREAD

**Issue by eileenpeppard** [erdl/survey_admin#60]
Hey, Guys,

I'm trying out survey admin and it won't let me log in.  Using this link:
https://csbcd01.soest.hawaii.edu/login#

-Eileen

**Comment by ryantanaka** [comment]
@eileenpeppard, let me add you to the database. I'll get back to you shortly.

**Comment by ryantanaka** [comment]
@eileenpeppard has been added and was able to successfully log in. Closing this issue.

**Comment by carlosparadis** [comment]
I figured that was the issue :^) Thanks for the nice solving time!

**Comment by ryantanaka** [comment]
@carlosparadis haha np,
fyi i just added you as well
